% Defferential Evolution Optimization Toolbox.
% Problem can be solved:
%   1. Unconstrained sigle/multiple object optimization.
%   2. Constrained single/multiple object optimization.
%   3. Constrain satisfaction problem.

% Author:
%       Yu XuanFei, Harbin Institute of Technology.
%       E-mail:     14b902037@hit.edu.cn

% Run the constrain satisfaction problem defined by the ObjfunModel.m
clear;  clc

DeInfo = struct('FunObjName', 'ObjfunModel',...
                'MaxGen',100,...
                'F',0.9,...
                'Cr',0.85,...
                'EqErr',1e-3,...
                'BaseVectorStrategy','best',...
                'ScaleFactorStrategy','dither-per-generation',...
                'ScaleFactorRandomizeMagnitude',0.1,...
                'EitherOrFactor',1,...
                'TargetToBestFactor',0.5,...
                'NBest',5);

figure(1); hold on; grid on; box on
for i = 1:100
[x_parent,fv_Obj,fv_Con,ExitFlag] = DE(DeInfo,[],0);
plot(x_parent(1,:),x_parent(2,:),'.')
end
%%
% Find the minimum value of function f(x,y) = x^2 + y^2
clear;  clc

DeInfo = struct('FunObjName', 'ObjfunExample',...
                'MaxGen',100,...
                'F',0.9,...
                'Cr',0.85,...
                'EqErr',1e-3,...
                'BaseVectorStrategy','best',...
                'ScaleFactorStrategy','dither-per-generation',...
                'ScaleFactorRandomizeMagnitude',0.1,...
                'EitherOrFactor',1,...
                'TargetToBestFactor',0.5,...
                'NBest',5);
            
[x_parent,fv_Obj,fv_Con,ExitFlag] = DE(DeInfo,[],1);

